ServerEvents.recipes(event =>{
    event.remove({ output: 'create:hand_crank' })
	event.remove({ output: '#excompressum:sieves'})
	event.remove({ input: '#excompressum:sieves'})
	event.remove({ output: '#excompressum:heavy_sieves'})
	event.remove({ input: '#excompressum:heavy_sieves'})
    event.remove({output: '#exdeorum:sieves'})	
	event.remove({output: '#exdeorum:heavy_sieves'})	
	event.remove({input: '#exdeorum:sieves'})
	event.remove({input: '#exdeorum:heavy_sieves'})	
	event.remove({id: 'projecte:watch_of_flowing_time'})
	event.remove({output: 'projectexpansion:cyan_power_flower'})
	event.remove({output: 'projectexpansion:green_power_flower'})
	event.remove({output: 'projectexpansion:lime_power_flower'})
	event.remove({output: 'projectexpansion:yellow_power_flower'})
	event.remove({output: 'projectexpansion:orange_power_flower'})
	event.remove({output: 'projectexpansion:white_power_flower'})
	event.remove({output: 'projectexpansion:fading_power_flower'})
	event.remove({output: 'projectexpansion:final_power_flower'})

	// remove archwood sieves
	event.remove('exdeorum:archwood_sieve')
	event.remove('exdeorum:blue_archwood_compressed_sieve')
	event.remove('exdeorum:green_archwood_compressed_sieve')
	event.remove('exdeorum:red_archwood_compressed_sieve')
	event.remove('exdeorum:purple_archwood_compressed_sieve')

	// Resource Capsules Mod
	event.remove({output: 'resource_capsules:tier_1_mini_capsule'})
	event.remove({output: 'resource_capsules:tier_2_mini_capsule'})
	event.remove({output: 'resource_capsules:tier_3_mini_capsule'})
	event.remove({input: 'resource_capsules:tier_1_mini_capsule'})
	event.remove({input: 'resource_capsules:tier_2_mini_capsule'})
	event.remove({input: 'resource_capsules:tier_3_mini_capsule'})
})