MMEvents.registerPorts(event => {
    // FLUID
    event.create('fluid_port')
    .name('Basic Fluid Port')
    .controllerId('mm:fuel_distillery')
    .config('mm:fluid', c => {
        c.rows(1)
        c.columns(1)
        c.slotCapacity(1000)
        c.autoPush(true)
        c.tierRank(1)
    })
    event.create('desh_fluid_port')
    .name('Desh Fluid Port')
    .controllerId('mm:desh_drill_controller')
    .config('mm:fluid', c => {
        c.rows(1)
        c.columns(1)
        c.slotCapacity(1000)
        c.autoPush(true)
        c.tierRank(2)
    })
    // ENERGY
    event.create('energy_port')
    .name('Basic Energy Port')
    .controllerId('mm:fuel_distillery')
    .config('mm:energy', c => {
        c.capacity(1000)
        c.maxReceive(1000)
        c.maxExtract(1000)
        c.autoPush(true)
        c.tierRank(1)
    })
    event.create('desh_energy_port')
    .name('Desh Energy Port')
    .controllerId('mm:desh_drill_controller')
    .config('mm:energy', c => {
        c.capacity(10000)
        c.maxReceive(10000)
        c.maxExtract(10000)
        c.autoPush(true)
        c.tierRank(2)
    })
    // ITEM
    event.create('item_port')
    .name('Basic Item Port')
    .controllerId('mm:t1_rocket_assembly_controller')
    .config('mm:item', c => {
        c.rows(3)
        c.columns(3)
        c.slotCapacity(64)
        c.tierRank(1)
    })
    event.create('desh_item_port')
    .name('Desh Item Port')
    .controllerId('mm:t2_rocket_assembly_controller')
    .config('mm:item', c => {
        c.rows(3)
        c.columns(3)
        c.slotCapacity(64)
        c.tierRank(2)
    })
})