#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Aug 27 17:58:56 BST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.8.1.zip
enableShaders=false
